//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trenirovka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agents
    {
        public int Id_agents { get; set; }
        public Nullable<int> Id_typeag { get; set; }
        public string Gmail { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Adress { get; set; }
        public Nullable<int> Prioretet { get; set; }
        public string FIO { get; set; }
        public Nullable<int> Inn { get; set; }
        public Nullable<int> Kpp { get; set; }
        public Nullable<int> Role_id { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Type_agents Type_agents { get; set; }
    }
}
